### ISSUE TITLE
Enzyme + React-Router => 😞

### ISSUE THREAD

**Issue by kyusu** [60frames/react-boilerplate#99]
Hi Richard,

first of all, thanks for the awesome react-boilerplate project. I especially appreciate the out of the box server-side rendering (which is sorely lacking from the 'create-react-app' project).
Maybe you are able to help me with problem I'm encountering. I've included [enzyme](https://airbnb.io/enzyme/) as it felt like a good addition to [jest](https://facebook.github.io/jest/) which is thankfully already present in your boilerplate setup.

I know want to test a Component which includes a `<Link to="/test">test</Link>` component.  But whenever I try to get it render with either [mount](http://airbnb.io/enzyme/docs/api/mount.html) or [render](http://airbnb.io/enzyme/docs/api/render.html) it is failing with:
```
Invariant Violation: link is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.
```

For some reason `<Link/>` is being interpreted as `<link/>`. I can not reproduce this with the 'create-react-app'. It feels I'm missing something here.

### Steps to reproduce
* I did checkout the react-boilerplate project
* I've added enzyme via `npm install --save-dev enzyme` (and ended up with version `2.9.1`)
* I wrote the following minimal test case
```javascript
import {render} from 'enzyme';
import React from 'react';
import {Link} from 'react-router';

describe('<Link/>', () => {
    it('renders without complaining', () => {
        render(<Link>test</Link>);
    });
});
```
The exact same test with the same version of enzyme works like a charm with `create-react-app` but so far I could not find out what is missing from react-boiler-plate.

I would appreciate any hints! Thanks!

**Comment by richardscarrott** [comment]
@kyusu ah yes, this is because react-router is mocked within `src/__mocks__/react-router.js` so `Link` and `Router` actually just export the string 'Link' and 'Router'...this even caught me out at first!

The thinking behind mocking `react-router`'s components was I like to effectively shallow render components by mocking non-built-in components but still use `react-test-renderer` for jest snapshots.

If you prefer not to use jest snapshots or are happy to take snapshots of deep trees then you can just delete `src/__mock__/react-router.js`.

**Comment by kyusu** [comment]
@richardscarrott Thanks for your answer. Now I'm embarrassed. How could I overlook something so obvious.
Thanks again for your boilerplate-code.
